"""
Week 11: Task Hierarchy Models

Hierarchical task breakdown from approved specifications:
Specification → Epic → Feature → Story → Task

Felix agent breaks down HLD specifications into actionable work items
with clear hierarchy and relationships.
"""

from sqlalchemy import Column, String, Integer, Text, DateTime, ForeignKey, Boolean, Float
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import relationship
from datetime import datetime
import uuid
from app.database import Base


# Status constants
class EpicStatus:
    """Epic lifecycle status"""
    DRAFT = "draft"
    PLANNED = "planned"
    IN_PROGRESS = "in_progress"
    COMPLETED = "completed"
    ON_HOLD = "on_hold"
    CANCELLED = "cancelled"


class FeatureStatus:
    """Feature lifecycle status"""
    DRAFT = "draft"
    PLANNED = "planned"
    IN_PROGRESS = "in_progress"
    COMPLETED = "completed"
    ON_HOLD = "on_hold"
    CANCELLED = "cancelled"


class StoryStatus:
    """User story lifecycle status"""
    DRAFT = "draft"
    READY = "ready"  # Ready for sprint planning
    IN_PROGRESS = "in_progress"
    IN_REVIEW = "in_review"
    DONE = "done"
    BLOCKED = "blocked"


class TaskStatus:
    """Technical task status"""
    TODO = "todo"
    IN_PROGRESS = "in_progress"
    IN_REVIEW = "in_review"
    DONE = "done"
    BLOCKED = "blocked"


# Priority levels (shared across all work items)
class Priority:
    """Work item priority levels"""
    CRITICAL = "critical"
    HIGH = "high"
    MEDIUM = "medium"
    LOW = "low"


class Epic(Base):
    """
    Epic: High-level business capability or major feature area.

    Examples:
    - User Management System
    - Payment Processing
    - Reporting Dashboard

    Generated by Felix from approved Specification.
    Contains 3-10 features.
    """
    __tablename__ = "task_epics"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    specification_id = Column(UUID(as_uuid=True), ForeignKey("green_paper_specifications.id", ondelete="CASCADE"), nullable=False, index=True)
    project_id = Column(String(50), ForeignKey("items.id", ondelete="CASCADE"), nullable=False, index=True)

    # Core fields
    title = Column(String(200), nullable=False, index=True)
    description = Column(Text, nullable=False)
    status = Column(String(20), nullable=False, default=EpicStatus.DRAFT, index=True)
    priority = Column(String(20), nullable=False, default=Priority.MEDIUM)

    # Business context
    business_value = Column(Text, nullable=True)  # Why this epic matters
    user_personas = Column(JSONB, nullable=True)  # ["Admin", "End User", "Developer"]
    acceptance_criteria = Column(JSONB, nullable=True)  # List of criteria

    # Planning & estimation
    estimated_story_points = Column(Integer, nullable=True)  # Sum of feature estimates
    estimated_weeks = Column(Integer, nullable=True)  # Duration estimate
    start_date = Column(DateTime, nullable=True)
    target_date = Column(DateTime, nullable=True)
    completion_date = Column(DateTime, nullable=True)

    # Tracking
    sequence_number = Column(Integer, nullable=False)  # Order within specification (1, 2, 3...)
    progress_percentage = Column(Integer, default=0)  # 0-100

    # Generation metadata
    generated_by = Column(String(50), default="Felix")
    generated_at = Column(DateTime, default=datetime.utcnow)
    generation_prompt = Column(Text, nullable=True)  # Prompt used for generation

    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    generation_metadata = Column(JSONB, nullable=True)  # dependencies, risks, notes

    # Relationships
    specification = relationship("Specification", foreign_keys=[specification_id])
    features = relationship("Feature", back_populates="epic", cascade="all, delete-orphan")

    def __repr__(self):
        return f"<Epic(id={self.id}, title='{self.title}', status='{self.status}', features={len(self.features)})>"


class Feature(Base):
    """
    Feature: Specific user-facing capability within an epic.

    Examples (within "User Management" epic):
    - User Registration
    - Password Reset
    - Profile Management

    Contains 3-8 user stories.
    """
    __tablename__ = "task_features"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    epic_id = Column(UUID(as_uuid=True), ForeignKey("task_epics.id", ondelete="CASCADE"), nullable=False, index=True)
    project_id = Column(String(50), ForeignKey("items.id", ondelete="CASCADE"), nullable=False, index=True)

    title = Column(String(200), nullable=False, index=True)
    description = Column(Text, nullable=False)
    status = Column(String(20), nullable=False, default=FeatureStatus.DRAFT, index=True)
    priority = Column(String(20), nullable=False, default=Priority.MEDIUM)

    # Technical details
    technical_approach = Column(Text, nullable=True)  # How to implement
    api_endpoints = Column(JSONB, nullable=True)  # Required API endpoints
    database_changes = Column(JSONB, nullable=True)  # Schema changes needed
    dependencies = Column(JSONB, nullable=True)  # Other features/epics this depends on

    # Estimation
    estimated_story_points = Column(Integer, nullable=True)
    estimated_days = Column(Integer, nullable=True)
    complexity = Column(String(20), nullable=True)  # "simple", "moderate", "complex"

    # Tracking
    sequence_number = Column(Integer, nullable=False)  # Order within epic
    progress_percentage = Column(Integer, default=0)

    generated_by = Column(String(50), default="Felix")
    generated_at = Column(DateTime, default=datetime.utcnow)

    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    generation_metadata = Column(JSONB, nullable=True)

    # Relationships
    epic = relationship("Epic", back_populates="features")
    stories = relationship("Story", back_populates="feature", cascade="all, delete-orphan")

    def __repr__(self):
        return f"<Feature(id={self.id}, title='{self.title}', status='{self.status}', stories={len(self.stories)})>"


class Story(Base):
    """
    User Story: Smallest deliverable user-facing value.

    Format: "As a [user type], I want [goal] so that [benefit]"

    Examples (within "User Registration" feature):
    - As a new user, I want to sign up with email so that I can access the platform
    - As a user, I want to verify my email so that my account is secure

    Contains 1-5 technical tasks.
    """
    __tablename__ = "task_stories"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    feature_id = Column(UUID(as_uuid=True), ForeignKey("task_features.id", ondelete="CASCADE"), nullable=False, index=True)
    project_id = Column(String(50), ForeignKey("items.id", ondelete="CASCADE"), nullable=False, index=True)

    title = Column(String(300), nullable=False, index=True)  # User story title
    description = Column(Text, nullable=False)  # Full user story

    # User story template fields
    user_type = Column(String(100), nullable=True)  # "Admin", "End User", etc.
    user_goal = Column(Text, nullable=True)  # What they want to do
    user_benefit = Column(Text, nullable=True)  # Why they want it

    status = Column(String(20), nullable=False, default=StoryStatus.DRAFT, index=True)
    priority = Column(String(20), nullable=False, default=Priority.MEDIUM)

    # Acceptance criteria (MUST be testable)
    acceptance_criteria = Column(JSONB, nullable=False)  # List of "Given/When/Then" criteria

    # Estimation (Planning Poker)
    story_points = Column(Integer, nullable=True)  # Fibonacci: 1, 2, 3, 5, 8, 13
    estimated_hours = Column(Float, nullable=True)  # Developer estimate
    actual_hours = Column(Float, nullable=True)  # Actual time spent

    # Sprint assignment
    sprint_id = Column(String(50), nullable=True, index=True)  # Which sprint this is in
    assigned_to = Column(String(100), nullable=True)  # Developer assigned

    # Tracking
    sequence_number = Column(Integer, nullable=False)  # Order within feature
    is_blocked = Column(Boolean, default=False)
    blocked_reason = Column(Text, nullable=True)

    generated_by = Column(String(50), default="Felix")
    generated_at = Column(DateTime, default=datetime.utcnow)

    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    completed_at = Column(DateTime, nullable=True)

    generation_metadata = Column(JSONB, nullable=True)

    # Relationships
    feature = relationship("Feature", back_populates="stories")
    tasks = relationship("Task", back_populates="story", cascade="all, delete-orphan")

    def __repr__(self):
        return f"<Story(id={self.id}, title='{self.title[:50]}', points={self.story_points}, status='{self.status}')>"


class Task(Base):
    """
    Task: Technical work item (no direct user value, enables stories).

    Examples (within a user story):
    - Create user registration API endpoint
    - Add email validation logic
    - Write unit tests for registration
    - Update database schema for users table

    Smallest work unit (typically 1-4 hours).
    """
    __tablename__ = "task_tasks"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    story_id = Column(UUID(as_uuid=True), ForeignKey("task_stories.id", ondelete="CASCADE"), nullable=False, index=True)
    project_id = Column(String(50), ForeignKey("items.id", ondelete="CASCADE"), nullable=False, index=True)

    title = Column(String(200), nullable=False, index=True)
    description = Column(Text, nullable=True)  # Optional for simple tasks
    status = Column(String(20), nullable=False, default=TaskStatus.TODO, index=True)
    priority = Column(String(20), nullable=False, default=Priority.MEDIUM)

    # Technical details
    task_type = Column(String(50), nullable=True)  # "backend", "frontend", "database", "testing", "devops"
    technical_notes = Column(Text, nullable=True)
    code_files = Column(JSONB, nullable=True)  # Files to be changed

    # Estimation
    estimated_hours = Column(Float, nullable=True)  # 0.5, 1, 2, 4
    actual_hours = Column(Float, nullable=True)

    # Tracking
    sequence_number = Column(Integer, nullable=False)  # Order within story
    assigned_to = Column(String(100), nullable=True)
    is_blocked = Column(Boolean, default=False)
    blocked_reason = Column(Text, nullable=True)

    # Git integration
    branch_name = Column(String(200), nullable=True)
    commit_sha = Column(String(40), nullable=True)
    pull_request_url = Column(String(500), nullable=True)

    generated_by = Column(String(50), default="Felix")
    generated_at = Column(DateTime, default=datetime.utcnow)

    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    completed_at = Column(DateTime, nullable=True)

    generation_metadata = Column(JSONB, nullable=True)

    # Relationships
    story = relationship("Story", back_populates="tasks")

    def __repr__(self):
        return f"<Task(id={self.id}, title='{self.title[:40]}', status='{self.status}', hours={self.estimated_hours})>"


# Note: Reverse relationship (Specification.epics) will be added in green_paper.py
# to avoid circular imports
