"""
Task Generation Models
Week 23-24 Implementation

Self-Questioning allows agents to generate their own training tasks
based on identified skill gaps, failures, and unexplored areas.
"""

from sqlalchemy import (
    Column, String, Integer, Float, Boolean, DateTime, Text,
    ForeignKey, Enum as SQLEnum, JSON
)
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import relationship
from datetime import datetime
import uuid
import enum

from app.database import Base


# =============================================================================
# Enums
# =============================================================================

class GeneratedTaskType(str, enum.Enum):
    """Types of training tasks agents can generate."""
    FAILURE_RETRY = "FAILURE_RETRY"
    EDGE_CASE_TEST = "EDGE_CASE_TEST"
    SKILL_EXPANSION = "SKILL_EXPANSION"
    VALIDATION_TEST = "VALIDATION_TEST"
    PATTERN_PRACTICE = "PATTERN_PRACTICE"
    EXPLORATION = "EXPLORATION"


class TaskDifficulty(str, enum.Enum):
    """Difficulty levels for training tasks."""
    EASY = "EASY"
    MEDIUM = "MEDIUM"
    HARD = "HARD"


class TaskStatus(str, enum.Enum):
    """Status of a training task."""
    PENDING = "PENDING"
    IN_PROGRESS = "IN_PROGRESS"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    SKIPPED = "SKIPPED"


class TaskSource(str, enum.Enum):
    """Source of task generation."""
    AGENT = "AGENT"
    ATTRIBUTION = "ATTRIBUTION"
    VALIDATION = "VALIDATION"
    EXPLORATION = "EXPLORATION"


class SkillGapSeverity(str, enum.Enum):
    """Severity levels for skill gaps."""
    CRITICAL = "CRITICAL"
    IMPORTANT = "IMPORTANT"
    MINOR = "MINOR"


class LessonType(str, enum.Enum):
    """Types of lessons learned from training."""
    SUCCESS = "SUCCESS"
    FAILURE = "FAILURE"
    INSIGHT = "INSIGHT"


class ImprovementTrend(str, enum.Enum):
    """Trend indicators for agent improvement."""
    IMPROVING = "IMPROVING"
    STABLE = "STABLE"
    DECLINING = "DECLINING"


# =============================================================================
# Models
# =============================================================================

class TrainingTask(Base):
    """
    A training task generated by or for an agent.

    Training tasks are used to help agents improve their skills by
    practicing on generated scenarios based on skill gaps, failures,
    or unexplored areas.
    """
    __tablename__ = "training_tasks"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    agent_id = Column(String(50), nullable=False, index=True)
    agent_name = Column(String(100), nullable=False)

    # Task type and classification
    task_type = Column(SQLEnum(GeneratedTaskType), nullable=False)
    difficulty = Column(SQLEnum(TaskDifficulty), default=TaskDifficulty.MEDIUM)
    source = Column(SQLEnum(TaskSource), nullable=False)
    status = Column(SQLEnum(TaskStatus), default=TaskStatus.PENDING)

    # Scenario details (stored as JSON)
    scenario_description = Column(Text, nullable=False)
    scenario_context = Column(JSON, default=dict)
    scenario_constraints = Column(JSON, default=list)  # List of strings
    scenario_success_criteria = Column(JSON, default=list)  # List of strings
    scenario_related_patterns = Column(JSON, default=list)  # Optional patterns
    scenario_focus_areas = Column(JSON, default=list)  # Optional focus areas

    # Expected outcome
    learning_objective = Column(Text)
    expected_success_rate = Column(Float, default=0.7)
    target_skills = Column(JSON, default=list)  # List of skill names
    improvement_metrics = Column(JSON, default=list)  # List of metric names

    # Links to other entities
    parent_attribution_id = Column(UUID(as_uuid=True), ForeignKey("attributions.id"), nullable=True)
    parent_validation_id = Column(String(100), nullable=True)
    skill_gap_id = Column(UUID(as_uuid=True), ForeignKey("skill_gaps.id"), nullable=True)

    # Priority and estimation
    priority = Column(Integer, default=50)  # 0-100, higher = more important
    estimated_duration_ms = Column(Integer, default=300000)  # 5 minutes default

    # Execution tracking
    execution_attempts = Column(Integer, default=0)
    max_attempts = Column(Integer, default=3)

    # Timestamps
    created_at = Column(DateTime, default=datetime.now)
    started_at = Column(DateTime, nullable=True)
    completed_at = Column(DateTime, nullable=True)

    # Relationships
    skill_gap = relationship("SkillGap", back_populates="training_tasks")
    results = relationship("TrainingTaskResult", back_populates="task")


class TrainingTaskResult(Base):
    """
    Result of executing a training task.

    Records what the agent learned, metrics, and any follow-up
    tasks that were generated.
    """
    __tablename__ = "training_task_results"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    task_id = Column(UUID(as_uuid=True), ForeignKey("training_tasks.id"), nullable=False)
    agent_id = Column(String(50), nullable=False, index=True)
    success = Column(Boolean, default=False)

    # Actual outcome (JSON fields)
    learning_achieved = Column(JSON, default=list)  # List of learnings
    skills_improved = Column(JSON, default=list)  # List of skill names
    unexpected_learnings = Column(JSON, default=list)  # Bonus learnings

    # Metrics
    duration_ms = Column(Integer)
    attempts = Column(Integer, default=1)
    validation_passed = Column(Boolean, default=False)
    confidence_score = Column(Float, default=0.0)

    # Lessons learned (stored as JSON array of lesson objects)
    lessons = Column(JSON, default=list)

    # Follow-up tasks (stored as JSON array of partial task definitions)
    follow_up_tasks = Column(JSON, default=list)

    # Link to attribution
    attribution_id = Column(UUID(as_uuid=True), nullable=True)

    # Timestamp
    completed_at = Column(DateTime, default=datetime.now)

    # Relationships
    task = relationship("TrainingTask", back_populates="results")


class SkillGap(Base):
    """
    An identified gap in agent skills.

    Skill gaps are identified through attribution analysis, validation
    failures, or low confidence scores on certain task types.
    """
    __tablename__ = "skill_gaps"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    agent_id = Column(String(50), nullable=False, index=True)
    agent_name = Column(String(100), nullable=False)

    # Gap description
    description = Column(Text, nullable=False)
    area = Column(String(100), nullable=False)  # Domain/area of the gap
    severity = Column(SQLEnum(SkillGapSeverity), default=SkillGapSeverity.IMPORTANT)

    # Evidence supporting this gap (JSON array of evidence objects)
    evidence = Column(JSON, default=list)

    # Status
    addressed = Column(Boolean, default=False)

    # Timestamps
    identified_at = Column(DateTime, default=datetime.now)
    addressed_at = Column(DateTime, nullable=True)

    # Relationships
    training_tasks = relationship("TrainingTask", back_populates="skill_gap")


class ExplorationTarget(Base):
    """
    A target area for environment exploration.

    Agents can explore codebase areas, patterns, technologies,
    or workflows they haven't encountered before.
    """
    __tablename__ = "exploration_targets"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)

    # Target identification
    target_type = Column(String(50), nullable=False)  # CODEBASE_AREA, PATTERN, TECHNOLOGY, WORKFLOW
    name = Column(String(200), nullable=False)
    reason = Column(Text)  # Why is this worth exploring?

    # Value assessment
    learning_value = Column(Float, default=0.5)  # 0-1

    # Status
    explored = Column(Boolean, default=False)

    # Related skill gaps (JSON array of skill gap IDs)
    related_skill_gaps = Column(JSON, default=list)

    # Timestamps
    created_at = Column(DateTime, default=datetime.now)
    explored_at = Column(DateTime, nullable=True)


class ImprovementMetric(Base):
    """
    Improvement metrics tracking for an agent over a period.

    Used to measure how well an agent is improving through
    self-questioning and training.
    """
    __tablename__ = "improvement_metrics"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    agent_id = Column(String(50), nullable=False, index=True)

    # Period
    period_start = Column(DateTime, nullable=False)
    period_end = Column(DateTime, nullable=False)

    # Task metrics
    tasks_generated = Column(Integer, default=0)
    tasks_completed = Column(Integer, default=0)
    tasks_successful = Column(Integer, default=0)
    tasks_failed = Column(Integer, default=0)

    # Learning metrics
    skill_gaps_identified = Column(Integer, default=0)
    skill_gaps_addressed = Column(Integer, default=0)
    lessons_learned = Column(Integer, default=0)
    patterns_discovered = Column(Integer, default=0)

    # Performance changes (relative, e.g., 0.15 = +15%)
    success_rate_change = Column(Float, default=0.0)
    confidence_change = Column(Float, default=0.0)
    estimation_accuracy_change = Column(Float, default=0.0)

    # Trend indicator
    trend = Column(SQLEnum(ImprovementTrend), default=ImprovementTrend.STABLE)

    # Timestamp
    created_at = Column(DateTime, default=datetime.now)


class TrainingSession(Base):
    """
    A training session groups multiple training tasks together.

    Sessions help track overall progress and outcomes from
    a batch of training activities.
    """
    __tablename__ = "training_sessions"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    agent_id = Column(String(50), nullable=False, index=True)

    # Timestamps
    started_at = Column(DateTime, default=datetime.now)
    completed_at = Column(DateTime, nullable=True)

    # Session content (JSON arrays of task IDs)
    task_ids = Column(JSON, default=list)
    result_ids = Column(JSON, default=list)

    # Session outcomes
    skill_gaps_addressed = Column(JSON, default=list)  # List of gap IDs
    new_skill_gaps_identified = Column(JSON, default=list)  # List of gap IDs
    overall_success = Column(Boolean, default=False)

    # Metrics before/after (JSON objects)
    metrics_before_session = Column(JSON, default=dict)
    metrics_after_session = Column(JSON, default=dict)


class GenerationStrategy(Base):
    """
    Strategy configuration for task generation per agent.

    Defines how an agent should generate training tasks for itself,
    including focus areas, difficulty preferences, and type weights.
    """
    __tablename__ = "generation_strategies"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    agent_id = Column(String(50), nullable=False, unique=True, index=True)

    # Configuration
    focus_areas = Column(JSON, default=list)  # List of area strings
    difficulty_preference = Column(SQLEnum(TaskDifficulty), default=TaskDifficulty.MEDIUM)
    max_tasks_per_session = Column(Integer, default=5)
    cooldown_period_ms = Column(Integer, default=3600000)  # 1 hour default

    # Type weights (JSON object mapping task type to weight)
    type_weights = Column(JSON, default=dict)

    # Timestamps
    created_at = Column(DateTime, default=datetime.now)
    updated_at = Column(DateTime, default=datetime.now, onupdate=datetime.now)
