"""
Generated Code Detector Service

Detects generated/auto-generated code in source repositories.
Used to separate generated code from handwritten code in analysis.

Strategy:
- Generated code: Include in security scans, volume metrics; EXCLUDE from quality metrics
- Handwritten code: Include in ALL metrics and scans

Detection methods:
1. Directory patterns (e.g., 'My Project/', 'node_modules/')
2. File patterns (e.g., '*.Designer.vb', 'Reference.cs')
3. Content markers (e.g., '<auto-generated>', 'DO NOT EDIT')

Week 158 - Created for Fase 1 Software Intake.
"""

import os
import re
from dataclasses import dataclass, field
from enum import Enum
from pathlib import Path
from typing import Dict, List, Optional, Set, Tuple
import yaml


class GeneratorType(str, Enum):
    """Types of code generators."""
    VISUAL_STUDIO_DESIGNER = "vs_designer"
    WINDOWS_FORMS = "windows_forms"
    WPF_XAML = "wpf_xaml"
    WCF_SERVICE = "wcf_service"
    WEB_SERVICE = "web_service"
    ENTITY_FRAMEWORK = "entity_framework"
    T4_TEMPLATE = "t4_template"
    PROTOCOL_BUFFERS = "protobuf"
    OPENAPI_SWAGGER = "openapi"
    GRAPHQL = "graphql"
    THRIFT = "thrift"
    BUILD_OUTPUT = "build_output"
    PACKAGE_MANAGER = "package_manager"
    MINIFIED = "minified"
    BUNDLED = "bundled"
    LOCK_FILE = "lock_file"
    RESOURCES = "resources"
    UNKNOWN = "unknown"


@dataclass
class GeneratedCodeMatch:
    """Result of generated code detection for a single file."""
    file_path: str
    is_generated: bool
    generator_type: GeneratorType = GeneratorType.UNKNOWN
    detection_method: str = ""  # "directory", "file_pattern", "content_marker"
    matched_pattern: str = ""  # The specific pattern that matched
    confidence: float = 1.0  # 0.0-1.0, lower for content-based detection


@dataclass
class GeneratedCodeSummary:
    """Summary of generated code detection for a project."""
    total_files: int = 0
    generated_files: int = 0
    handwritten_files: int = 0
    generated_loc: int = 0
    handwritten_loc: int = 0
    by_generator_type: Dict[str, int] = field(default_factory=dict)
    by_directory: Dict[str, int] = field(default_factory=dict)
    by_detection_method: Dict[str, int] = field(default_factory=dict)
    generated_file_list: List[GeneratedCodeMatch] = field(default_factory=list)


class GeneratedCodeDetector:
    """
    Service for detecting generated/auto-generated code.

    Uses three detection methods in order of specificity:
    1. Directory patterns - Most reliable, entire directories are generated
    2. File patterns - Based on extensions and filenames
    3. Content markers - Check file headers for generation markers
    """

    # Directory patterns that indicate generated code
    GENERATED_DIRECTORIES: Dict[str, GeneratorType] = {
        # .NET / Visual Studio
        "My Project": GeneratorType.VISUAL_STUDIO_DESIGNER,
        "Service References": GeneratorType.WCF_SERVICE,
        "Web References": GeneratorType.WEB_SERVICE,
        "Connected Services": GeneratorType.WCF_SERVICE,
        "obj": GeneratorType.BUILD_OUTPUT,
        "bin": GeneratorType.BUILD_OUTPUT,

        # JavaScript/TypeScript
        "node_modules": GeneratorType.PACKAGE_MANAGER,
        "dist": GeneratorType.BUILD_OUTPUT,
        "build": GeneratorType.BUILD_OUTPUT,
        ".next": GeneratorType.BUILD_OUTPUT,
        ".nuxt": GeneratorType.BUILD_OUTPUT,

        # Go
        "vendor": GeneratorType.PACKAGE_MANAGER,

        # Python
        "site-packages": GeneratorType.PACKAGE_MANAGER,
        ".venv": GeneratorType.PACKAGE_MANAGER,
        "venv": GeneratorType.PACKAGE_MANAGER,
        "__pycache__": GeneratorType.BUILD_OUTPUT,
        ".eggs": GeneratorType.BUILD_OUTPUT,
        "*.egg-info": GeneratorType.BUILD_OUTPUT,

        # Generic
        "Generated": GeneratorType.UNKNOWN,
        "__generated__": GeneratorType.UNKNOWN,
        "auto-generated": GeneratorType.UNKNOWN,
        "autogen": GeneratorType.UNKNOWN,
    }

    # File extension patterns
    GENERATED_EXTENSIONS: Dict[str, GeneratorType] = {
        # .NET
        ".Designer.vb": GeneratorType.WINDOWS_FORMS,
        ".Designer.cs": GeneratorType.WINDOWS_FORMS,
        ".designer.vb": GeneratorType.WINDOWS_FORMS,
        ".designer.cs": GeneratorType.WINDOWS_FORMS,
        ".g.cs": GeneratorType.WPF_XAML,
        ".g.vb": GeneratorType.WPF_XAML,
        ".g.i.cs": GeneratorType.WPF_XAML,
        ".g.i.vb": GeneratorType.WPF_XAML,
        ".generated.cs": GeneratorType.T4_TEMPLATE,
        ".generated.vb": GeneratorType.T4_TEMPLATE,
        ".tt.cs": GeneratorType.T4_TEMPLATE,
        ".edmx.cs": GeneratorType.ENTITY_FRAMEWORK,
        ".edmx.vb": GeneratorType.ENTITY_FRAMEWORK,

        # Protocol Buffers
        ".pb.go": GeneratorType.PROTOCOL_BUFFERS,
        ".pb.cc": GeneratorType.PROTOCOL_BUFFERS,
        ".pb.h": GeneratorType.PROTOCOL_BUFFERS,
        "_pb2.py": GeneratorType.PROTOCOL_BUFFERS,
        "_pb2_grpc.py": GeneratorType.PROTOCOL_BUFFERS,

        # gRPC
        ".grpc.pb.go": GeneratorType.PROTOCOL_BUFFERS,
        ".grpc.pb.cc": GeneratorType.PROTOCOL_BUFFERS,

        # GraphQL
        ".graphql.ts": GeneratorType.GRAPHQL,
        ".graphql.js": GeneratorType.GRAPHQL,
        ".generated.ts": GeneratorType.GRAPHQL,
        ".generated.tsx": GeneratorType.GRAPHQL,

        # Minified/Bundled
        ".min.js": GeneratorType.MINIFIED,
        ".min.css": GeneratorType.MINIFIED,
        ".bundle.js": GeneratorType.BUNDLED,
        ".chunk.js": GeneratorType.BUNDLED,
    }

    # Exact file names that are generated
    GENERATED_FILENAMES: Dict[str, GeneratorType] = {
        # .NET Service References
        "Reference.vb": GeneratorType.WEB_SERVICE,
        "Reference.cs": GeneratorType.WEB_SERVICE,
        "Reference.svcmap": GeneratorType.WCF_SERVICE,

        # Resources
        "Resources.Designer.cs": GeneratorType.RESOURCES,
        "Resources.Designer.vb": GeneratorType.RESOURCES,
        "Settings.Designer.cs": GeneratorType.RESOURCES,
        "Settings.Designer.vb": GeneratorType.RESOURCES,

        # Lock files
        "package-lock.json": GeneratorType.LOCK_FILE,
        "yarn.lock": GeneratorType.LOCK_FILE,
        "pnpm-lock.yaml": GeneratorType.LOCK_FILE,
        "Cargo.lock": GeneratorType.LOCK_FILE,
        "poetry.lock": GeneratorType.LOCK_FILE,
        "Pipfile.lock": GeneratorType.LOCK_FILE,
        "composer.lock": GeneratorType.LOCK_FILE,
        "Gemfile.lock": GeneratorType.LOCK_FILE,
        "go.sum": GeneratorType.LOCK_FILE,
        "packages.lock.json": GeneratorType.LOCK_FILE,

        # Other
        "AssemblyInfo.cs": GeneratorType.VISUAL_STUDIO_DESIGNER,
        "AssemblyInfo.vb": GeneratorType.VISUAL_STUDIO_DESIGNER,
    }

    # Content markers that indicate generated code
    CONTENT_MARKERS_EXACT: List[Tuple[str, GeneratorType, float]] = [
        # (marker, generator_type, confidence)
        ("<auto-generated>", GeneratorType.VISUAL_STUDIO_DESIGNER, 1.0),
        ("</auto-generated>", GeneratorType.VISUAL_STUDIO_DESIGNER, 1.0),
        ("DO NOT EDIT", GeneratorType.UNKNOWN, 0.9),
        ("DO NOT MODIFY", GeneratorType.UNKNOWN, 0.9),
    ]

    CONTENT_MARKERS_CONTAINS: List[Tuple[str, GeneratorType, float]] = [
        # (marker substring, generator_type, confidence)
        ("Auto-generated", GeneratorType.UNKNOWN, 0.95),
        ("auto-generated", GeneratorType.UNKNOWN, 0.95),
        ("AUTO GENERATED", GeneratorType.UNKNOWN, 0.95),
        ("This code was generated", GeneratorType.UNKNOWN, 0.95),
        ("Generated by", GeneratorType.UNKNOWN, 0.9),
        ("machine generated", GeneratorType.UNKNOWN, 0.9),
        ("automatically generated", GeneratorType.UNKNOWN, 0.9),
        ("Autogenerated by", GeneratorType.UNKNOWN, 0.9),
        ("Generated from", GeneratorType.UNKNOWN, 0.85),

        # Visual Studio / .NET specific
        ("ResXFileCodeGenerator", GeneratorType.RESOURCES, 1.0),
        ("SettingsSingleFileGenerator", GeneratorType.RESOURCES, 1.0),
        ("StronglyTypedResourceBuilder", GeneratorType.RESOURCES, 1.0),
        ("Windows Form Designer generated code", GeneratorType.WINDOWS_FORMS, 1.0),
        ("InitializeComponent", GeneratorType.WINDOWS_FORMS, 0.8),

        # Web Services
        ("wsdl.exe", GeneratorType.WEB_SERVICE, 1.0),
        ("svcutil.exe", GeneratorType.WCF_SERVICE, 1.0),
        ("System.Web.Services.Protocols", GeneratorType.WEB_SERVICE, 0.8),

        # Entity Framework
        ("Entity Framework", GeneratorType.ENTITY_FRAMEWORK, 0.7),
        ("EdmRelationshipAttribute", GeneratorType.ENTITY_FRAMEWORK, 1.0),

        # Protocol Buffers
        ("Generated by the protocol buffer compiler", GeneratorType.PROTOCOL_BUFFERS, 1.0),
        ("protoc-gen", GeneratorType.PROTOCOL_BUFFERS, 1.0),
        ("Google.Protobuf", GeneratorType.PROTOCOL_BUFFERS, 0.9),

        # Thrift
        ("Autogenerated by Thrift Compiler", GeneratorType.THRIFT, 1.0),
        ("APACHE_THRIFT", GeneratorType.THRIFT, 0.9),

        # OpenAPI/Swagger
        ("OpenAPI Generator", GeneratorType.OPENAPI_SWAGGER, 1.0),
        ("swagger-codegen", GeneratorType.OPENAPI_SWAGGER, 1.0),
        ("NSwag", GeneratorType.OPENAPI_SWAGGER, 1.0),

        # GraphQL
        ("graphql-codegen", GeneratorType.GRAPHQL, 1.0),
        ("GraphQL Code Generator", GeneratorType.GRAPHQL, 1.0),

        # Other
        ("Generated by Cython", GeneratorType.UNKNOWN, 1.0),
        ("Generated by jison", GeneratorType.UNKNOWN, 1.0),
        ("gRPC C++ plugin", GeneratorType.PROTOCOL_BUFFERS, 1.0),
    ]

    # How many bytes to read from file header for content detection
    HEADER_BYTES = 2048

    def __init__(self, custom_config_path: Optional[str] = None):
        """
        Initialize the detector.

        Args:
            custom_config_path: Optional path to YAML config with custom patterns.
        """
        self._custom_directories: Dict[str, GeneratorType] = {}
        self._custom_extensions: Dict[str, GeneratorType] = {}
        self._custom_filenames: Dict[str, GeneratorType] = {}
        self._custom_markers: List[Tuple[str, GeneratorType, float]] = []

        if custom_config_path:
            self._load_custom_config(custom_config_path)

    def _load_custom_config(self, config_path: str) -> None:
        """Load custom patterns from YAML configuration."""
        try:
            with open(config_path, 'r') as f:
                config = yaml.safe_load(f)

            if not config:
                return

            # Load custom directories
            for dir_name in config.get('directories', []):
                self._custom_directories[dir_name] = GeneratorType.UNKNOWN

            # Load custom file extensions
            for ext in config.get('file_extensions', []):
                self._custom_extensions[ext] = GeneratorType.UNKNOWN

            # Load custom filenames
            for name in config.get('file_names', []):
                self._custom_filenames[name] = GeneratorType.UNKNOWN

            # Load custom content markers
            markers = config.get('content_markers', {})
            for marker in markers.get('exact', []):
                self._custom_markers.append((marker, GeneratorType.UNKNOWN, 1.0))
            for marker in markers.get('contains', []):
                self._custom_markers.append((marker, GeneratorType.UNKNOWN, 0.9))

        except Exception:
            # Silently ignore config errors, use defaults
            pass

    def is_generated_directory(self, path: str) -> Tuple[bool, Optional[str], GeneratorType]:
        """
        Check if file is in a generated directory.

        Returns: (is_generated, matched_directory, generator_type)
        """
        path_parts = Path(path).parts

        # Check each directory component
        for part in path_parts:
            # Check built-in patterns
            if part in self.GENERATED_DIRECTORIES:
                return True, part, self.GENERATED_DIRECTORIES[part]

            # Check custom patterns
            if part in self._custom_directories:
                return True, part, self._custom_directories[part]

            # Check glob-style patterns (e.g., "*.egg-info")
            for pattern, gen_type in self.GENERATED_DIRECTORIES.items():
                if '*' in pattern:
                    import fnmatch
                    if fnmatch.fnmatch(part, pattern):
                        return True, pattern, gen_type

        return False, None, GeneratorType.UNKNOWN

    def is_generated_file_pattern(self, filename: str) -> Tuple[bool, Optional[str], GeneratorType]:
        """
        Check if file matches a generated file pattern.

        Returns: (is_generated, matched_pattern, generator_type)
        """
        # Check exact filenames first
        if filename in self.GENERATED_FILENAMES:
            return True, filename, self.GENERATED_FILENAMES[filename]
        if filename in self._custom_filenames:
            return True, filename, self._custom_filenames[filename]

        # Check extension patterns (longer patterns first for specificity)
        all_extensions = {**self.GENERATED_EXTENSIONS, **self._custom_extensions}
        sorted_extensions = sorted(all_extensions.keys(), key=len, reverse=True)

        for ext in sorted_extensions:
            if filename.endswith(ext):
                return True, ext, all_extensions[ext]

        return False, None, GeneratorType.UNKNOWN

    def is_generated_by_content(
        self,
        file_path: str,
        content: Optional[str] = None
    ) -> Tuple[bool, Optional[str], GeneratorType, float]:
        """
        Check file content for generation markers.

        Args:
            file_path: Path to file
            content: Optional pre-loaded content (if None, reads from file)

        Returns: (is_generated, matched_marker, generator_type, confidence)
        """
        if content is None:
            try:
                with open(file_path, 'r', encoding='utf-8', errors='ignore') as f:
                    content = f.read(self.HEADER_BYTES)
            except Exception:
                return False, None, GeneratorType.UNKNOWN, 0.0
        else:
            # Only check the header portion
            content = content[:self.HEADER_BYTES]

        # Check exact markers first
        all_exact = self.CONTENT_MARKERS_EXACT + [
            m for m in self._custom_markers if m[2] == 1.0
        ]
        for marker, gen_type, confidence in all_exact:
            if marker in content:
                return True, marker, gen_type, confidence

        # Check contains markers
        all_contains = self.CONTENT_MARKERS_CONTAINS + [
            m for m in self._custom_markers if m[2] < 1.0
        ]
        for marker, gen_type, confidence in all_contains:
            if marker in content:
                return True, marker, gen_type, confidence

        return False, None, GeneratorType.UNKNOWN, 0.0

    def detect_file(
        self,
        file_path: str,
        check_content: bool = True,
        content: Optional[str] = None
    ) -> GeneratedCodeMatch:
        """
        Detect if a single file is generated code.

        Args:
            file_path: Path to the file
            check_content: Whether to check file content (slower but more accurate)
            content: Optional pre-loaded content to avoid re-reading

        Returns: GeneratedCodeMatch with detection results
        """
        filename = os.path.basename(file_path)

        # 1. Check directory patterns (most reliable)
        is_gen, matched, gen_type = self.is_generated_directory(file_path)
        if is_gen:
            return GeneratedCodeMatch(
                file_path=file_path,
                is_generated=True,
                generator_type=gen_type,
                detection_method="directory",
                matched_pattern=matched or "",
                confidence=1.0
            )

        # 2. Check file patterns
        is_gen, matched, gen_type = self.is_generated_file_pattern(filename)
        if is_gen:
            return GeneratedCodeMatch(
                file_path=file_path,
                is_generated=True,
                generator_type=gen_type,
                detection_method="file_pattern",
                matched_pattern=matched or "",
                confidence=1.0
            )

        # 3. Check content markers (optional, slower)
        if check_content:
            is_gen, matched, gen_type, confidence = self.is_generated_by_content(
                file_path, content
            )
            if is_gen:
                return GeneratedCodeMatch(
                    file_path=file_path,
                    is_generated=True,
                    generator_type=gen_type,
                    detection_method="content_marker",
                    matched_pattern=matched or "",
                    confidence=confidence
                )

        # Not generated
        return GeneratedCodeMatch(
            file_path=file_path,
            is_generated=False,
            generator_type=GeneratorType.UNKNOWN,
            detection_method="",
            matched_pattern="",
            confidence=0.0
        )

    def analyze_directory(
        self,
        root_path: str,
        check_content: bool = True,
        file_extensions: Optional[Set[str]] = None,
        skip_directories: Optional[Set[str]] = None,
    ) -> GeneratedCodeSummary:
        """
        Analyze an entire directory for generated code.

        Args:
            root_path: Root directory to analyze
            check_content: Whether to check file content for markers
            file_extensions: Optional set of extensions to check (e.g., {'.cs', '.vb'})
            skip_directories: Additional directories to skip entirely

        Returns: GeneratedCodeSummary with aggregated results
        """
        summary = GeneratedCodeSummary()
        skip_dirs = skip_directories or set()

        # Always skip these
        skip_dirs.update({'.git', '.svn', '.hg', '__pycache__'})

        for dirpath, dirnames, filenames in os.walk(root_path):
            # Filter out directories to skip
            dirnames[:] = [d for d in dirnames if d not in skip_dirs]

            for filename in filenames:
                # Filter by extension if specified
                if file_extensions:
                    ext = os.path.splitext(filename)[1].lower()
                    if ext not in file_extensions:
                        continue

                file_path = os.path.join(dirpath, filename)
                rel_path = os.path.relpath(file_path, root_path)

                # Detect if generated
                match = self.detect_file(file_path, check_content=check_content)
                summary.total_files += 1

                if match.is_generated:
                    summary.generated_files += 1
                    summary.generated_file_list.append(match)

                    # Count by generator type
                    gen_type = match.generator_type.value
                    summary.by_generator_type[gen_type] = \
                        summary.by_generator_type.get(gen_type, 0) + 1

                    # Count by detection method
                    summary.by_detection_method[match.detection_method] = \
                        summary.by_detection_method.get(match.detection_method, 0) + 1

                    # Count by directory
                    if match.detection_method == "directory":
                        summary.by_directory[match.matched_pattern] = \
                            summary.by_directory.get(match.matched_pattern, 0) + 1

                    # Count LOC (rough estimate)
                    try:
                        with open(file_path, 'r', encoding='utf-8', errors='ignore') as f:
                            loc = sum(1 for line in f if line.strip())
                            summary.generated_loc += loc
                    except Exception:
                        pass
                else:
                    summary.handwritten_files += 1
                    try:
                        with open(file_path, 'r', encoding='utf-8', errors='ignore') as f:
                            loc = sum(1 for line in f if line.strip())
                            summary.handwritten_loc += loc
                    except Exception:
                        pass

        return summary

    def generate_gitattributes(self) -> str:
        """
        Generate .gitattributes content to mark generated code for GitHub Linguist.
        """
        lines = [
            "# Generated code markers for GitHub Linguist",
            "# See: https://github.com/github-linguist/linguist/blob/main/docs/overrides.md",
            "",
            "# Directory exclusions",
        ]

        for dir_name in sorted(self.GENERATED_DIRECTORIES.keys()):
            if '*' not in dir_name:
                lines.append(f"**/{dir_name}/** linguist-generated=true")

        lines.extend(["", "# File pattern exclusions"])

        for ext in sorted(self.GENERATED_EXTENSIONS.keys()):
            lines.append(f"*{ext} linguist-generated=true")

        for filename in sorted(self.GENERATED_FILENAMES.keys()):
            lines.append(f"{filename} linguist-generated=true")

        return "\n".join(lines) + "\n"

    def generate_sonar_exclusions(self) -> str:
        """
        Generate SonarQube exclusion patterns for sonar-project.properties.
        """
        patterns = []

        # Directories
        for dir_name in self.GENERATED_DIRECTORIES.keys():
            if '*' not in dir_name:
                patterns.append(f"**/{dir_name}/**")

        # File patterns
        for ext in self.GENERATED_EXTENSIONS.keys():
            patterns.append(f"**/*{ext}")

        for filename in self.GENERATED_FILENAMES.keys():
            patterns.append(f"**/{filename}")

        exclusion = ",".join(patterns)

        return f"""# Generated code exclusions
sonar.exclusions={exclusion}
sonar.coverage.exclusions={exclusion}
sonar.cpd.exclusions={exclusion}
"""
