"""
Base Adapter - Week 101

Abstract base class for LLM-specific context adapters.
"""

from abc import ABC, abstractmethod
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from ..project_context import ProjectContext


class BaseAdapter(ABC):
    """
    Abstract base class for LLM context adapters.

    Each adapter transforms a universal ProjectContext into
    a provider-specific format optimized for that LLM.
    """

    @property
    @abstractmethod
    def provider_name(self) -> str:
        """Return the provider name (e.g., 'claude', 'codex')."""
        pass

    @property
    @abstractmethod
    def output_filename(self) -> str:
        """Return the output filename for this adapter."""
        pass

    @property
    def output_directory(self) -> str:
        """Return the output directory (default: .{provider_name}/)."""
        return f".{self.provider_name}"

    @abstractmethod
    def transform(self, context: "ProjectContext") -> str:
        """
        Transform ProjectContext to provider-specific format.

        Args:
            context: Universal ProjectContext object

        Returns:
            String content in provider-specific format
        """
        pass

    def get_output_path(self) -> str:
        """Get full output path for the context file."""
        return f"{self.output_directory}/{self.output_filename}"

    def _format_list(self, items: list, prefix: str = "-") -> str:
        """Format a list with given prefix."""
        if not items:
            return ""
        return "\n".join(f"{prefix} {item}" for item in items)

    def _format_dict(self, data: dict, indent: int = 0) -> str:
        """Format a dictionary with indentation."""
        if not data:
            return ""
        prefix = "  " * indent
        lines = []
        for key, value in data.items():
            if isinstance(value, dict):
                lines.append(f"{prefix}{key}:")
                lines.append(self._format_dict(value, indent + 1))
            elif isinstance(value, list):
                lines.append(f"{prefix}{key}:")
                for item in value:
                    lines.append(f"{prefix}  - {item}")
            else:
                lines.append(f"{prefix}{key}: {value}")
        return "\n".join(lines)


class UniversalAdapter(BaseAdapter):
    """
    Universal fallback adapter.

    Used when no provider-specific adapter is available.
    Outputs standard markdown format.
    """

    @property
    def provider_name(self) -> str:
        return "universal"

    @property
    def output_filename(self) -> str:
        return "CONTEXT.md"

    def transform(self, context: "ProjectContext") -> str:
        """Transform to universal markdown format."""
        return f"""# Project Context: {context.project_name}

## Tech Stack
- Language: {context.tech_stack.primary_language}
- Framework: {context.tech_stack.framework}
- Database: {context.tech_stack.database}

## Architecture
- Style: {context.architecture.style}
- Layers: {context.architecture.layers}
- API: {context.architecture.api_style}

## Security
- Auth: {context.security.authentication}
- Authorization: {context.security.authorization}

## Implementation Order
{self._format_list(context.implementation_order, "1.")}

## Guidelines

### Do's
{self._format_list(context.dos)}

### Don'ts
{self._format_list(context.donts)}

---
Generated by MarQed.ai LLM Context Adapter
"""
