"""
Qwen Adapter - Week 101

Transforms ProjectContext to Qwen-optimized structured sections.
Output: QWEN.md (root level for visibility)
"""

from typing import TYPE_CHECKING
from .base import BaseAdapter

if TYPE_CHECKING:
    from ..project_context import ProjectContext


class QwenAdapter(BaseAdapter):
    """
    Qwen-specific context adapter.

    Features:
    - Structured sections format
    - Chinese-capable (bilingual support)
    - Technical depth optimized
    - Clear hierarchical organization
    """

    @property
    def provider_name(self) -> str:
        return "qwen"

    @property
    def output_filename(self) -> str:
        return "QWEN.md"

    @property
    def output_directory(self) -> str:
        # Qwen uses root directory for visibility
        return "."

    def transform(self, context: "ProjectContext") -> str:
        """Transform to Qwen structured sections format."""

        # Build domain table
        domain_table = "| 术语 (Term) | 定义 (Definition) | 代码实体 (Entity) |\n|-------------|-------------------|-------------------|\n"
        if context.domain_vocabulary:
            for t in context.domain_vocabulary:
                domain_table += f"| {t.term} | {t.definition} | {t.code_entity} |\n"
        else:
            domain_table += "| - | - | - |\n"

        # Build compliance table
        compliance_list = "\n".join(
            f"- [x] {c}" for c in context.security.compliance_requirements
        ) if context.security.compliance_requirements else "- [ ] 无合规要求 (No compliance requirements)"

        return f"""# 项目上下文 / Project Context: {context.project_name}

**版本 / Version:** {context.version}
**状态 / Status:** {context.status}

---

## 1. 技术栈 / Tech Stack

| 组件 (Component) | 技术 (Technology) |
|------------------|-------------------|
| 主语言 (Language) | {context.tech_stack.primary_language} |
| 框架 (Framework) | {context.tech_stack.framework} |
| 数据库 (Database) | {context.tech_stack.database} |
| 缓存 (Cache) | {context.tech_stack.cache} |
| 消息队列 (Queue) | {context.tech_stack.message_queue} |

---

## 2. 架构模式 / Architecture Pattern

| 属性 (Property) | 值 (Value) |
|-----------------|------------|
| 风格 (Style) | {context.architecture.style} |
| 分层 (Layers) | {context.architecture.layers} |
| API风格 (API) | {context.architecture.api_style} |

---

## 3. 安全模型 / Security Model

| 属性 (Property) | 值 (Value) |
|-----------------|------------|
| 认证 (Authentication) | {context.security.authentication} |
| 授权 (Authorization) | {context.security.authorization} |

### 合规要求 / Compliance Requirements
{compliance_list}

---

## 4. 命名规范 / Naming Conventions

| 类型 (Type) | 规范 (Convention) | 示例 (Example) |
|-------------|-------------------|----------------|
| 类 (Classes) | {context.naming_conventions.classes} | `UserService` |
| 函数 (Functions) | {context.naming_conventions.functions} | `get_user_by_id` |
| 文件 (Files) | {context.naming_conventions.files} | `user_service.py` |
| 常量 (Constants) | {context.naming_conventions.constants} | `MAX_RETRY` |
| 私有字段 (Private) | {context.naming_conventions.private_fields} | `_cache` |

---

## 5. 领域词汇表 / Domain Vocabulary

{domain_table}

---

## 6. 实现顺序 / Implementation Order

{self._format_numbered_bilingual(context.implementation_order)}

---

## 7. 开发指南 / Development Guidelines

### 应该做 / Do's
{self._format_bullet_list(context.dos)}

### 不应该做 / Don'ts
{self._format_bullet_list(context.donts)}

---

## 8. 实现前检查 / Pre-Implementation Checklist

{self._format_bullet_list(context.questions_to_ask)}

---

**生成者 / Generated by:** MarQed.ai LLM Context Adapter
**适配器 / Adapter:** Qwen (Structured Sections)
"""

    def _format_numbered_bilingual(self, items: list) -> str:
        """Format as numbered list."""
        if not items:
            return "1. 无特定顺序 / No specific order"
        return "\n".join(f"{i+1}. {item}" for i, item in enumerate(items))

    def _format_bullet_list(self, items: list) -> str:
        """Format as bullet list."""
        if not items:
            return "- 无 / None"
        return "\n".join(f"- {item}" for item in items)
