/**
 * Task Generation Types for Self-Questioning Agents
 * Week 23-24 Implementation
 *
 * Self-Questioning allows agents to generate their own training tasks
 * based on identified skill gaps, failures, and unexplored areas.
 */

// =============================================================================
// Enums
// =============================================================================

export enum GeneratedTaskType {
  /** Retry a previously failed task with adjusted approach */
  FAILURE_RETRY = 'FAILURE_RETRY',
  /** Test edge cases derived from successful patterns */
  EDGE_CASE_TEST = 'EDGE_CASE_TEST',
  /** Expand agent skills into new areas */
  SKILL_EXPANSION = 'SKILL_EXPANSION',
  /** Generate validation test cases */
  VALIDATION_TEST = 'VALIDATION_TEST',
  /** Practice applying known patterns */
  PATTERN_PRACTICE = 'PATTERN_PRACTICE',
  /** Explore unexplored areas of the codebase */
  EXPLORATION = 'EXPLORATION'
}

export enum TaskDifficulty {
  EASY = 'EASY',
  MEDIUM = 'MEDIUM',
  HARD = 'HARD'
}

export enum TaskStatus {
  PENDING = 'PENDING',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  SKIPPED = 'SKIPPED'
}

export enum TaskSource {
  /** Generated by the agent itself */
  AGENT = 'AGENT',
  /** Generated by the system based on attribution */
  ATTRIBUTION = 'ATTRIBUTION',
  /** Generated from validation failures */
  VALIDATION = 'VALIDATION',
  /** Generated from environment exploration */
  EXPLORATION = 'EXPLORATION'
}

export enum SkillGapSeverity {
  CRITICAL = 'CRITICAL',
  IMPORTANT = 'IMPORTANT',
  MINOR = 'MINOR'
}

// =============================================================================
// Core Interfaces
// =============================================================================

/**
 * A scenario describing the context for a training task
 */
export interface TaskScenario {
  /** Human-readable description of the scenario */
  description: string;
  /** Contextual data for the task */
  context: Record<string, any>;
  /** Constraints that must be satisfied */
  constraints: string[];
  /** Criteria for successful completion */
  successCriteria: string[];
  /** Optional: Related patterns to apply */
  relatedPatterns?: string[];
  /** Optional: Files or areas to focus on */
  focusAreas?: string[];
}

/**
 * Expected outcome for a training task
 */
export interface ExpectedOutcome {
  /** What should the agent learn from this task? */
  learningObjective: string;
  /** Expected success rate (0-1) */
  expectedSuccessRate: number;
  /** Skills that should improve */
  targetSkills: string[];
  /** Metrics to measure improvement */
  improvementMetrics: string[];
}

/**
 * A training task generated by or for an agent
 */
export interface TrainingTask {
  id: string;
  agentId: string;
  agentName: string;
  taskType: GeneratedTaskType;
  scenario: TaskScenario;
  expectedOutcome: ExpectedOutcome;
  difficulty: TaskDifficulty;
  source: TaskSource;
  status: TaskStatus;

  /** Link to attribution that triggered this task (if any) */
  parentAttributionId?: string;
  /** Link to validation failure that triggered this task */
  parentValidationId?: string;
  /** Link to skill gap this addresses */
  skillGapId?: string;

  /** Priority score (higher = more important) */
  priority: number;
  /** Estimated time to complete (ms) */
  estimatedDuration: number;

  /** Timestamps */
  createdAt: Date;
  startedAt?: Date;
  completedAt?: Date;

  /** Execution metadata */
  executionAttempts: number;
  maxAttempts: number;
}

/**
 * Result of executing a training task
 */
export interface TrainingTaskResult {
  taskId: string;
  agentId: string;
  success: boolean;

  /** Actual outcome vs expected */
  actualOutcome: {
    learningAchieved: string[];
    skillsImproved: string[];
    unexpectedLearnings: string[];
  };

  /** Performance metrics */
  metrics: {
    duration: number;
    attempts: number;
    validationPassed: boolean;
    confidenceScore: number;
  };

  /** Lessons learned */
  lessons: TrainingLesson[];

  /** Generated follow-up tasks (if any) */
  followUpTasks: Partial<TrainingTask>[];

  /** Link to attribution for this result */
  attributionId?: string;

  completedAt: Date;
}

/**
 * A lesson learned from training
 */
export interface TrainingLesson {
  lessonId: string;
  type: 'SUCCESS' | 'FAILURE' | 'INSIGHT';
  description: string;
  applicableScenarios: string[];
  confidence: number;
}

// =============================================================================
// Skill Gap Tracking
// =============================================================================

/**
 * An identified gap in agent skills
 */
export interface SkillGap {
  id: string;
  agentId: string;
  agentName: string;

  /** Description of the skill gap */
  description: string;
  /** Area/domain of the gap */
  area: string;
  /** How severe is this gap? */
  severity: SkillGapSeverity;

  /** Evidence supporting this gap */
  evidence: SkillGapEvidence[];

  /** Has this gap been addressed? */
  addressed: boolean;
  /** Training tasks generated to address this gap */
  generatedTaskIds: string[];

  /** When was this gap identified? */
  identifiedAt: Date;
  /** When was this gap addressed? */
  addressedAt?: Date;
}

/**
 * Evidence supporting a skill gap
 */
export interface SkillGapEvidence {
  type: 'ATTRIBUTION_FAILURE' | 'VALIDATION_FAILURE' | 'LOW_CONFIDENCE' | 'PATTERN_MISSING';
  sourceId: string;
  description: string;
  timestamp: Date;
}

// =============================================================================
// Environment Exploration
// =============================================================================

/**
 * A target area for environment exploration
 */
export interface ExplorationTarget {
  id: string;
  /** Type of target */
  type: 'CODEBASE_AREA' | 'PATTERN' | 'TECHNOLOGY' | 'WORKFLOW';
  /** Name/identifier of the target */
  name: string;
  /** Why is this worth exploring? */
  reason: string;
  /** Estimated learning value (0-1) */
  learningValue: number;
  /** Has this been explored? */
  explored: boolean;
  /** Related skill gaps */
  relatedSkillGaps: string[];
}

/**
 * Comparison between projects for learning
 */
export interface ProjectComparison {
  currentProject: string;
  similarProject: string;
  similarityScore: number;
  differences: {
    area: string;
    currentApproach: string;
    alternativeApproach: string;
    potentialImprovement: string;
  }[];
  suggestedTasks: Partial<TrainingTask>[];
}

// =============================================================================
// Generation Strategies
// =============================================================================

/**
 * Strategy for generating tasks for a specific agent
 */
export interface GenerationStrategy {
  agentId: string;
  /** Areas to focus task generation on */
  focusAreas: string[];
  /** Preferred difficulty distribution */
  difficultyPreference: TaskDifficulty;
  /** Maximum tasks to generate per session */
  maxTasksPerSession: number;
  /** Minimum time between similar tasks (ms) */
  cooldownPeriod: number;
  /** Weight factors for different task types */
  typeWeights: Record<GeneratedTaskType, number>;
}

/**
 * Default generation strategies per agent
 */
export const DEFAULT_AGENT_STRATEGIES: Record<string, GenerationStrategy> = {
  felix_001: {
    agentId: 'felix_001',
    focusAreas: ['architecture', 'specifications', 'system_design'],
    difficultyPreference: TaskDifficulty.HARD,
    maxTasksPerSession: 5,
    cooldownPeriod: 3600000, // 1 hour
    typeWeights: {
      [GeneratedTaskType.FAILURE_RETRY]: 0.3,
      [GeneratedTaskType.EDGE_CASE_TEST]: 0.25,
      [GeneratedTaskType.SKILL_EXPANSION]: 0.2,
      [GeneratedTaskType.VALIDATION_TEST]: 0.1,
      [GeneratedTaskType.PATTERN_PRACTICE]: 0.1,
      [GeneratedTaskType.EXPLORATION]: 0.05
    }
  },
  marcus_001: {
    agentId: 'marcus_001',
    focusAreas: ['refactoring', 'technical_debt', 'code_maintenance'],
    difficultyPreference: TaskDifficulty.MEDIUM,
    maxTasksPerSession: 6,
    cooldownPeriod: 3600000,
    typeWeights: {
      [GeneratedTaskType.FAILURE_RETRY]: 0.25,
      [GeneratedTaskType.EDGE_CASE_TEST]: 0.15,
      [GeneratedTaskType.SKILL_EXPANSION]: 0.15,
      [GeneratedTaskType.VALIDATION_TEST]: 0.15,
      [GeneratedTaskType.PATTERN_PRACTICE]: 0.2,
      [GeneratedTaskType.EXPLORATION]: 0.1
    }
  },
  quinn_001: {
    agentId: 'quinn_001',
    focusAreas: ['security', 'quality', 'code_review'],
    difficultyPreference: TaskDifficulty.HARD,
    maxTasksPerSession: 8,
    cooldownPeriod: 1800000, // 30 minutes
    typeWeights: {
      [GeneratedTaskType.FAILURE_RETRY]: 0.2,
      [GeneratedTaskType.EDGE_CASE_TEST]: 0.3,
      [GeneratedTaskType.SKILL_EXPANSION]: 0.1,
      [GeneratedTaskType.VALIDATION_TEST]: 0.25,
      [GeneratedTaskType.PATTERN_PRACTICE]: 0.1,
      [GeneratedTaskType.EXPLORATION]: 0.05
    }
  },
  betty_001: {
    agentId: 'betty_001',
    focusAreas: ['debugging', 'error_handling', 'root_cause_analysis'],
    difficultyPreference: TaskDifficulty.HARD,
    maxTasksPerSession: 4,
    cooldownPeriod: 3600000,
    typeWeights: {
      [GeneratedTaskType.FAILURE_RETRY]: 0.35,
      [GeneratedTaskType.EDGE_CASE_TEST]: 0.25,
      [GeneratedTaskType.SKILL_EXPANSION]: 0.1,
      [GeneratedTaskType.VALIDATION_TEST]: 0.1,
      [GeneratedTaskType.PATTERN_PRACTICE]: 0.15,
      [GeneratedTaskType.EXPLORATION]: 0.05
    }
  },
  eliza_001: {
    agentId: 'eliza_001',
    focusAreas: ['estimation', 'complexity_analysis', 'prediction'],
    difficultyPreference: TaskDifficulty.MEDIUM,
    maxTasksPerSession: 5,
    cooldownPeriod: 7200000, // 2 hours
    typeWeights: {
      [GeneratedTaskType.FAILURE_RETRY]: 0.3,
      [GeneratedTaskType.EDGE_CASE_TEST]: 0.2,
      [GeneratedTaskType.SKILL_EXPANSION]: 0.15,
      [GeneratedTaskType.VALIDATION_TEST]: 0.1,
      [GeneratedTaskType.PATTERN_PRACTICE]: 0.2,
      [GeneratedTaskType.EXPLORATION]: 0.05
    }
  },
  tessa_001: {
    agentId: 'tessa_001',
    focusAreas: ['testing', 'test_strategy', 'coverage'],
    difficultyPreference: TaskDifficulty.MEDIUM,
    maxTasksPerSession: 7,
    cooldownPeriod: 1800000,
    typeWeights: {
      [GeneratedTaskType.FAILURE_RETRY]: 0.2,
      [GeneratedTaskType.EDGE_CASE_TEST]: 0.35,
      [GeneratedTaskType.SKILL_EXPANSION]: 0.1,
      [GeneratedTaskType.VALIDATION_TEST]: 0.2,
      [GeneratedTaskType.PATTERN_PRACTICE]: 0.1,
      [GeneratedTaskType.EXPLORATION]: 0.05
    }
  },
  miguel_001: {
    agentId: 'miguel_001',
    focusAreas: ['migration', 'platform_upgrades', 'compatibility'],
    difficultyPreference: TaskDifficulty.HARD,
    maxTasksPerSession: 3,
    cooldownPeriod: 7200000,
    typeWeights: {
      [GeneratedTaskType.FAILURE_RETRY]: 0.3,
      [GeneratedTaskType.EDGE_CASE_TEST]: 0.2,
      [GeneratedTaskType.SKILL_EXPANSION]: 0.2,
      [GeneratedTaskType.VALIDATION_TEST]: 0.15,
      [GeneratedTaskType.PATTERN_PRACTICE]: 0.1,
      [GeneratedTaskType.EXPLORATION]: 0.05
    }
  },
  diana_001: {
    agentId: 'diana_001',
    focusAreas: ['documentation', 'api_docs', 'user_guides'],
    difficultyPreference: TaskDifficulty.EASY,
    maxTasksPerSession: 6,
    cooldownPeriod: 3600000,
    typeWeights: {
      [GeneratedTaskType.FAILURE_RETRY]: 0.2,
      [GeneratedTaskType.EDGE_CASE_TEST]: 0.15,
      [GeneratedTaskType.SKILL_EXPANSION]: 0.2,
      [GeneratedTaskType.VALIDATION_TEST]: 0.1,
      [GeneratedTaskType.PATTERN_PRACTICE]: 0.25,
      [GeneratedTaskType.EXPLORATION]: 0.1
    }
  },
  peter_001: {
    agentId: 'peter_001',
    focusAreas: ['requirements', 'user_stories', 'business_analysis'],
    difficultyPreference: TaskDifficulty.MEDIUM,
    maxTasksPerSession: 5,
    cooldownPeriod: 3600000,
    typeWeights: {
      [GeneratedTaskType.FAILURE_RETRY]: 0.25,
      [GeneratedTaskType.EDGE_CASE_TEST]: 0.2,
      [GeneratedTaskType.SKILL_EXPANSION]: 0.2,
      [GeneratedTaskType.VALIDATION_TEST]: 0.1,
      [GeneratedTaskType.PATTERN_PRACTICE]: 0.15,
      [GeneratedTaskType.EXPLORATION]: 0.1
    }
  },
  paul_001: {
    agentId: 'paul_001',
    focusAreas: ['planning', 'coordination', 'risk_management'],
    difficultyPreference: TaskDifficulty.MEDIUM,
    maxTasksPerSession: 4,
    cooldownPeriod: 7200000,
    typeWeights: {
      [GeneratedTaskType.FAILURE_RETRY]: 0.25,
      [GeneratedTaskType.EDGE_CASE_TEST]: 0.15,
      [GeneratedTaskType.SKILL_EXPANSION]: 0.2,
      [GeneratedTaskType.VALIDATION_TEST]: 0.1,
      [GeneratedTaskType.PATTERN_PRACTICE]: 0.2,
      [GeneratedTaskType.EXPLORATION]: 0.1
    }
  }
};

// =============================================================================
// Metrics & Progress
// =============================================================================

/**
 * Improvement metrics for an agent
 */
export interface ImprovementMetrics {
  agentId: string;
  period: {
    start: Date;
    end: Date;
  };

  /** Task completion metrics */
  tasksGenerated: number;
  tasksCompleted: number;
  tasksSuccessful: number;
  tasksFailed: number;

  /** Learning metrics */
  skillGapsIdentified: number;
  skillGapsAddressed: number;
  lessonsLearned: number;
  patternsDiscovered: number;

  /** Performance improvements */
  successRateChange: number;  // -1 to 1 (e.g., 0.15 = +15%)
  confidenceChange: number;
  estimationAccuracyChange: number;

  /** Trend indicator */
  trend: 'IMPROVING' | 'STABLE' | 'DECLINING';
}

/**
 * Training session summary
 */
export interface TrainingSession {
  sessionId: string;
  agentId: string;
  startedAt: Date;
  completedAt?: Date;

  /** Tasks in this session */
  tasks: TrainingTask[];
  results: TrainingTaskResult[];

  /** Session outcomes */
  skillGapsAddressed: string[];
  newSkillGapsIdentified: string[];
  overallSuccess: boolean;

  /** Metrics delta */
  metricsBeforeSession: Partial<ImprovementMetrics>;
  metricsAfterSession: Partial<ImprovementMetrics>;
}

// =============================================================================
// API Request/Response Types
// =============================================================================

export interface GenerateTasksRequest {
  agentId: string;
  /** Override default strategy */
  strategy?: Partial<GenerationStrategy>;
  /** Focus on specific skill gaps */
  targetSkillGaps?: string[];
  /** Maximum number of tasks to generate */
  maxTasks?: number;
}

export interface GenerateTasksResponse {
  tasks: TrainingTask[];
  skillGapsTargeted: SkillGap[];
  estimatedTrainingTime: number;
}

export interface ExecuteTaskRequest {
  taskId: string;
  /** Override max attempts */
  maxAttempts?: number;
}

export interface ExecuteTaskResponse {
  result: TrainingTaskResult;
  experienceUpdated: boolean;
  followUpTasksGenerated: number;
}

export interface GetSkillGapsRequest {
  agentId: string;
  /** Filter by severity */
  minSeverity?: SkillGapSeverity;
  /** Include addressed gaps */
  includeAddressed?: boolean;
}

export interface GetSkillGapsResponse {
  skillGaps: SkillGap[];
  totalGaps: number;
  criticalGaps: number;
  addressedGaps: number;
}

export interface GetMetricsRequest {
  agentId: string;
  periodDays?: number;
}

export interface GetMetricsResponse {
  metrics: ImprovementMetrics;
  historicalMetrics: ImprovementMetrics[];
}
